spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event?characterEncoding=UTF-8
    password: 269842
    username: root


mybatis:
  configuration:
    map-underscore-to-camel-case: true